name: Version Index

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      package_version:
        description: "Version of the package to fetch"
        required: false
        default: ""

jobs:
  go-get:
    name: Install Go Package with Released Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Get Newest Tag
        run: |
          GOPROXY=https://proxy.golang.org GO111MODULE=on go list -m github.com/i5heu/ouroboros-db@`echo $(git describe --tags --abbrev=0)`