name: Version Index

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  go-get:
    name: Install Go Package with Released Version
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        uses: battila7/get-version-action@v2.2.1

      - name: Fetch Go Package Info
        uses: fjogeleit/http-request-action@v1.15.5
        with:
          url: "https://proxy.golang.org/github.com/i5heu/ouroborosdb/@latest"

      - name: Send Another HTTP Request
        uses: fjogeleit/http-request-action@v1.15.5
        with:
          url: "https://proxy.golang.org/github.com/i5heu/ouroboros-db/@v/v{{ steps.get-version.outputs.version }}.info"
